#!/bin/sh
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":1000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":2000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":3000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":4000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":5000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":6000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":7000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
curl -H "Content-Type: application/json" -X POST -d '{"action":"flight-search-with-budget","actor":{"id":"@tista","kind":"person"},"meta":{"number":8000000,"currency":"IDR","passengers":{"adults":1,"children":0,"infants":0},"dates":{"outbound":"2016-11-18","inbound":"2016-11-20"},"origin": "CGK-sky"},"object":{"id":"IDR-1500000","kind":"currency-number"}}' https://api.travelonbudget.co/v1/events
